USB_VID = 0x239A
USB_PID = 0x80B0
USB_PRODUCT = "Fluff M0"
USB_MANUFACTURER = "Radomir Dopieralski"

CHIP_VARIANT = SAMD21E18A
CHIP_FAMILY = samd21

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_FULL_BUILD = 0
CIRCUITPY_NEOPIXEL_WRITE = 1
CIRCUITPY_PIXELBUF = 1
CIRCUITPY_ROTARYIO = 1
CIRCUITPY_RTC = 0
CIRCUITPY_STORAGE = 0

SUPEROPT_GC = 1

CFLAGS_BOARD = --param max-inline-insns-auto=15

CIRCUITPY_USB_MIDI = 0
CIRCUITPY_USB_MSC = 0
CIRCUITPY_USB_CDC = 0
CIRCUITPY_USB_VENDOR = 0

CIRCUITPY_USB_HID = 1
CIRCUITPY_USB_HID_CONSUMER = 1
CIRCUITPY_USB_HID_KEYBOARD = 1
CIRCUITPY_USB_HID_MOUSE = 1
CIRCUITPY_USB_HID_SYS_CONTROL = 1
CIRCUITPY_USB_HID_GAMEPAD = 1
CIRCUITPY_USB_HID_DIGITIZER = 0
CIRCUITPY_USB_HID_XAC_COMPATIBLE_GAMEPAD = 0
